// Base de datos de personajes para el juego "¿Quién soy?".
// Cada categoría es un grupo de nombres famosos. En el juego también se cuelan,
// muy de vez en cuando, los nombres de los del propio viaje (incluido tú mismo 😈).
// Añade, quita o cambia lo que quieras: es solo una lista de strings.

export const CATEGORIAS = [
  {
    id: 'futbol',
    label: 'Futbolistas',
    emoji: '⚽',
    personajes: [
      'Messi',
      'Cristiano Ronaldo',
      'Vinícius Jr.',
      'Kylian Mbappé',
      'Erling Haaland',
      'Neymar',
      'Robert Lewandowski',
      'Jude Bellingham',
      'Lamine Yamal',
      'Pedri',
      'Gavi',
      'Rodri',
      'Nico Williams',
      'Dani Olmo',
      'Lautaro Martínez',
      'Julián Álvarez',
      'Antoine Griezmann',
      'Kevin De Bruyne',
      'Mohamed Salah',
      'Harry Kane',
      'Luka Modrić',
      'Thibaut Courtois',
      'Khvicha Kvaratskhelia',
      'Florian Wirtz',
      'Raphinha',
      'Bukayo Saka',
      'Phil Foden',
      'Federico Valverde',
      'Virgil van Dijk',
      'Achraf Hakimi',
      'Victor Osimhen',
      'Endrick',
      'Karim Benzema',
      'Toni Kroos',
      'Sergio Ramos',
      'Gerard Piqué',
      'Andrés Iniesta',
      'Xavi Hernández',
      'Iker Casillas',
      'Ronaldinho',
      'Zlatan Ibrahimović',
      'Luis Suárez',
      'Ángel Di María',
    ],
  },
  {
    id: 'streamers',
    label: 'Streamers e influencers',
    emoji: '🎮',
    personajes: [
      // España
      'Ibai Llanos',
      'AuronPlay',
      'TheGrefg',
      'ElRubius',
      'Vegetta777',
      'Willyrex',
      'DjMaRiiO',
      'ElXokas',
      'Knekro',
      'IlloJuan',
      'Cristinini',
      'Folagor',
      'Lolito',
      'Nil Ojeda',
      'Perxitaa',
      'Spursito',
      'Mixwell',
      'Werlyb',
      'Alexby11',
      'Mangel',
      'Reven',
      'Outconsumer',
      'Carola',
      // Latinoamérica
      'Spreen',
      'Coscu',
      'Goncho',
      'Davoo Xeneize',
      'Momo',
      'Luzu',
      'Robleis',
      'Rivers_gg',
      'AriGameplays',
      'ElMariana',
      'Juan Guarnizo',
      'Westcol',
      'Luisito Comunica',
      'Fernanfloo',
      'Germán Garmendia',
      'Kimberly Loaiza',
      'Domelipa',
      'Kunno',
      'Quackity',
    ],
  },
  {
    id: 'deportistas',
    label: 'Deportistas españoles',
    emoji: '🏅',
    personajes: [
      'Rafa Nadal',
      'Carlos Alcaraz',
      'Fernando Alonso',
      'Carlos Sainz',
      'Marc Márquez',
      'Álex Márquez',
      'Jorge Lorenzo',
      'Dani Pedrosa',
      'Joan Mir',
      'Pau Gasol',
      'Marc Gasol',
      'Ricky Rubio',
      'Sergio Llull',
      'Juan Carlos Navarro',
      'Alexia Putellas',
      'Aitana Bonmatí',
      'Jenni Hermoso',
      'Carolina Marín',
      'Garbiñe Muguruza',
      'Paula Badosa',
      'David Ferrer',
      'Jon Rahm',
      'Sergio García',
      'Mireia Belmonte',
      'Saúl Craviotto',
      'Lydia Valentín',
      'Ruth Beitia',
      'Ona Carbonell',
      'Maialen Chourraut',
      'Kilian Jornet',
      'Javier Fernández',
      'Teresa Perales',
      'Edurne Pasaban',
    ],
  },
  {
    id: 'musica',
    label: 'Música',
    emoji: '🎤',
    personajes: [
      'Bad Bunny',
      'Shakira',
      'Rosalía',
      'Karol G',
      'J Balvin',
      'Daddy Yankee',
      'Maluma',
      'Feid',
      'Rauw Alejandro',
      'Quevedo',
      'Bizarrap',
      'Duki',
      'Peso Pluma',
      'Aitana',
      'C. Tangana',
      'David Bisbal',
      'Alejandro Sanz',
      'Enrique Iglesias',
      'Ozuna',
      'Anuel AA',
      'Nicki Nicole',
      'Tini',
      'Manuel Turizo',
      'Sebastián Yatra',
      'Camilo',
      'Becky G',
      'Lola Índigo',
      'Melendi',
      'Estopa',
      'Pablo Alborán',
      'Rels B',
    ],
  },
  {
    id: 'cine',
    label: 'Cine y series',
    emoji: '🎬',
    personajes: [
      'Antonio Banderas',
      'Penélope Cruz',
      'Javier Bardem',
      'Mario Casas',
      'Úrsula Corberó',
      'Álvaro Morte',
      'Pedro Alonso',
      'Najwa Nimri',
      'Jaime Lorente',
      'Miguel Herrán',
      'Hugo Silva',
      'Paco León',
      'Santiago Segura',
      'Dani Rovira',
      'Blanca Suárez',
      'Ester Expósito',
      'Aron Piper',
      'Itziar Ituño',
      'Eduard Fernández',
      'Luis Tosar',
    ],
  },
  {
    id: 'ficcion',
    label: 'Ficción y dibujos',
    emoji: '🦸',
    personajes: [
      'Spider-Man',
      'Batman',
      'Superman',
      'Iron Man',
      'Hulk',
      'Capitán América',
      'Darth Vader',
      'Yoda',
      'Gandalf',
      'Harry Potter',
      'Joker',
      'Goku',
      'Pikachu',
      'Mario Bros',
      'Sonic',
      'Shrek',
      'Bob Esponja',
      'Homer Simpson',
      'Bart Simpson',
      'Mickey Mouse',
      'Doraemon',
      'Shin Chan',
      'Buzz Lightyear',
      'Woody',
      'Elsa (Frozen)',
    ],
  },
]
